"""Agent-readable Markdown rendering of the assessment.

profile.md / report.md are derived-only renderings a user can hand to an
LLM. The shared (exported) version is rendered from the redacted JSON, so
it must carry no code, paths, or private sections.
"""

import json
from pathlib import Path

from cruise_ai.markdown_export import profile_to_markdown

ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = json.loads((ROOT / "cruise_ai" / "examples" / "profile.json").read_text())


def test_profile_markdown_has_core_sections():
    md = profile_to_markdown(EXAMPLE, "profile")
    assert md.startswith("# ")
    assert "AI coding profile" in md
    assert "## How well you build with AI" in md
    assert "| Dimension | Score |" in md
    # six dimensions rendered
    assert md.count("/100 |") + md.count("insufficient |") >= 6


def test_report_markdown_is_deeper_than_profile():
    rep = profile_to_markdown(EXAMPLE, "report")
    prof = profile_to_markdown(EXAMPLE, "profile")
    assert "AI coding report" in rep
    # report carries evidence column + narrative-derived sections when present
    assert "| Evidence |" in rep
    assert len(rep) > len(prof)


def test_null_score_renders_insufficient_never_zero():
    p = json.loads(json.dumps(EXAMPLE))
    p["dimensions"]["signal_clarity"]["score"] = None
    md = profile_to_markdown(p, "profile")
    # the nulled row says insufficient; no "0/100" fabricated
    assert "insufficient" in md
    assert "Signal Clarity | 0/100" not in md


def test_shared_markdown_leaks_no_code_or_paths():
    from cruise_ai.schema import build_shareable_profile

    shareable = build_shareable_profile(EXAMPLE, {})
    md = profile_to_markdown(shareable, "report")
    assert "/Users/" not in md and "\\Users\\" not in md
    assert "```" not in md  # no code fences / source
    # footer states the derived-only contract
    assert "never change a score" in md


def test_markdown_always_ends_with_provenance_footer():
    for view in ("profile", "report"):
        md = profile_to_markdown(EXAMPLE, view)
        assert "Generated by cruise_ai from local signals" in md
