"""The generated derivations doc must stay in lockstep with the registry.

DERIVATIONS.md is @generated from nextmillionai/methodology_spec.py (which is
guarded against the scoring engine). This test re-renders it and asserts the
committed file matches — so the doc, the /methodology explorer, and the code can
never disagree. If it fails: run scripts/render_methodology_registry.py and commit.
"""

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "nextmillionai" / "docs" / "methodology" / "DERIVATIONS.md"
SCRIPT = ROOT / "scripts" / "render_methodology_registry.py"


def _load_renderer():
    spec = importlib.util.spec_from_file_location("render_methodology_registry", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_derivations_doc_is_up_to_date():
    renderer = _load_renderer()
    assert DOC.exists(), "DERIVATIONS.md missing — run scripts/render_methodology_registry.py"
    assert DOC.read_text() == renderer.render(), (
        "DERIVATIONS.md is stale vs the registry — run "
        "`python3 scripts/render_methodology_registry.py` and commit."
    )


def test_derivations_doc_is_generated_only():
    # Guard the @generated marker so nobody hand-edits it.
    assert "@generated by scripts/render_methodology_registry.py" in DOC.read_text()
