#!/usr/bin/env python3
"""Methodology change proposals — draft, review, compare, publish.

A file-based RFC workflow for *suggested* changes to the scoring
methodology or any other tunable parameter. It exists because the
versioned contracts (scoring formulas, the JSON schema, the three
version constants) are hardlines — see ``docs/HARDLINES.md`` — and must
never move as a side effect. A proposal makes the *intended* change
explicit and reviewable BEFORE any line of the engine moves:

    draft → under-review → accepted | rejected | superseded

Nothing here edits the engine. A proposal only records what a change
would be (param: current → proposed), its evidence, and its blast
radius. Landing an accepted proposal is still a separate, deliberate,
signed-off commit (HARDLINES §6).

Each proposal is ``docs/proposals/NNNN-slug.md``: a fenced ```json
metadata block at the top, then a free markdown body (Motivation,
Design, Evidence, Alternatives, Risks). The index and the version
cross-checks make the directory the single source of truth for what is
on the table.

Usage:
    python3 scripts/proposals.py new "Tighten the active-time gap"
    python3 scripts/proposals.py validate            # schema + staleness
    python3 scripts/proposals.py compare 0001        # current → proposed table
    python3 scripts/proposals.py render              # (re)write the index
    python3 scripts/proposals.py check               # CI: validate + index fresh
    python3 scripts/proposals.py status 0001 under-review
"""

from __future__ import annotations

import datetime as _dt
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROPOSALS_DIR = ROOT / "docs" / "proposals"
INDEX = PROPOSALS_DIR / "README.md"
TEMPLATE = PROPOSALS_DIR / "TEMPLATE.md"

STATUSES = ["draft", "under-review", "accepted", "rejected", "superseded"]
OPEN_STATUSES = {"draft", "under-review"}
DECIDED_STATUSES = {"accepted", "rejected", "superseded"}
VERSION_KEYS = ("methodology", "schema", "taxonomy")

_FILENAME_RE = re.compile(r"^(\d{4})-[a-z0-9][a-z0-9-]*\.md$")
_JSON_BLOCK_RE = re.compile(r"```json\b[^\n]*\n(.*?)\n```", re.DOTALL)
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_BUMP_RE = re.compile(r"^\s*(\S+)\s*->\s*(\S+)\s*$")

_GEN_HEADER = (
    "<!-- @generated by scripts/proposals.py — DO NOT EDIT.\n"
    "Add/edit a proposal under docs/proposals/ and run "
    "`python3 scripts/proposals.py render`. -->"
)


# ── live version constants (single source of truth) ──────────────────────────
def live_versions() -> dict[str, str]:
    """The current engine version constants, imported live so a proposal's
    declared base can be cross-checked against reality."""
    sys.path.insert(0, str(ROOT))
    from cruise_ai.schema import (  # noqa: PLC0415 — intentional late import
        METHODOLOGY_VERSION,
        SCHEMA_VERSION,
        TAXONOMY_VERSION,
    )

    return {
        "methodology": METHODOLOGY_VERSION,
        "schema": SCHEMA_VERSION,
        "taxonomy": TAXONOMY_VERSION,
    }


# ── parsing ──────────────────────────────────────────────────────────────────
def parse(path: Path) -> dict:
    """Return ``{"meta": dict, "body": str, "path": Path}`` for a proposal."""
    text = path.read_text()
    m = _JSON_BLOCK_RE.search(text)
    if not m:
        raise ValueError(f"{path.name}: no ```json metadata block found")
    try:
        meta = json.loads(m.group(1))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path.name}: metadata block is not valid JSON — {exc}") from exc
    body = text[m.end() :].strip()
    return {"meta": meta, "body": body, "path": path}


def discover() -> list[dict]:
    """All numbered proposals (excludes TEMPLATE and the index), id-sorted."""
    if not PROPOSALS_DIR.exists():
        return []
    out = []
    for p in sorted(PROPOSALS_DIR.glob("*.md")):
        if _FILENAME_RE.match(p.name):
            out.append(parse(p))
    return out


# ── validation ───────────────────────────────────────────────────────────────
def validate_one(rec: dict, live: dict[str, str]) -> list[str]:
    meta, path = rec["meta"], rec["path"]
    errs: list[str] = []

    def need(field: str) -> object:
        if field not in meta or meta[field] in (None, "", []):
            errs.append(f"{path.name}: missing required field '{field}'")
            return None
        return meta[field]

    fid = need("id")
    fm = _FILENAME_RE.match(path.name)
    if fid is not None and fm and fid != fm.group(1):
        errs.append(f"{path.name}: id '{fid}' does not match filename prefix '{fm.group(1)}'")

    need("title")
    need("summary")

    status = meta.get("status")
    if status not in STATUSES:
        errs.append(f"{path.name}: status '{status}' not in {STATUSES}")

    authors = meta.get("authors")
    if not isinstance(authors, list) or not authors:
        errs.append(f"{path.name}: 'authors' must be a non-empty list")

    opened = meta.get("opened")
    if not isinstance(opened, str) or not _DATE_RE.match(opened):
        errs.append(f"{path.name}: 'opened' must be an ISO date (YYYY-MM-DD)")

    if status in DECIDED_STATUSES and not meta.get("decided"):
        errs.append(f"{path.name}: status '{status}' requires a 'decided' date")

    # target_versions — keys legal, values null or "A -> B"; base must be live.
    tv = meta.get("target_versions")
    if not isinstance(tv, dict):
        errs.append(f"{path.name}: 'target_versions' must be an object")
    else:
        for k, v in tv.items():
            if k not in VERSION_KEYS:
                errs.append(f"{path.name}: target_versions key '{k}' not in {VERSION_KEYS}")
                continue
            if v is None:
                continue
            bump = _BUMP_RE.match(str(v))
            if not bump:
                errs.append(f"{path.name}: target_versions.{k} '{v}' must read 'A -> B'")
                continue
            base, _ = bump.group(1), bump.group(2)
            if status in OPEN_STATUSES and base != live[k]:
                errs.append(
                    f"{path.name}: target_versions.{k} base '{base}' is stale — live "
                    f"{k.upper()}_VERSION is '{live[k]}'. Rebase the proposal."
                )

    # changes — each item fully specified.
    changes = meta.get("changes")
    if not isinstance(changes, list) or not changes:
        errs.append(f"{path.name}: 'changes' must be a non-empty list")
    else:
        for i, c in enumerate(changes):
            if not isinstance(c, dict):
                errs.append(f"{path.name}: changes[{i}] must be an object")
                continue
            for key in ("param", "current", "proposed", "rationale"):
                if not str(c.get(key, "")).strip():
                    errs.append(f"{path.name}: changes[{i}] missing '{key}'")

    if not isinstance(meta.get("blast_radius"), list) or not meta.get("blast_radius"):
        errs.append(f"{path.name}: 'blast_radius' must be a non-empty list")

    if not rec["body"]:
        errs.append(f"{path.name}: empty body — keep the Motivation/Design sections")

    return errs


def validate_all() -> tuple[list[dict], list[str]]:
    recs = discover()
    live = live_versions()
    errs: list[str] = []
    seen: dict[str, str] = {}
    for rec in recs:
        fid = rec["meta"].get("id")
        if fid in seen:
            errs.append(f"duplicate id '{fid}' in {rec['path'].name} and {seen[fid]}")
        elif fid:
            seen[fid] = rec["path"].name
        errs += validate_one(rec, live)
    return recs, errs


# ── rendering ────────────────────────────────────────────────────────────────
def _status_label(s: str) -> str:
    return {
        "draft": "Draft",
        "under-review": "Under review",
        "accepted": "Accepted",
        "rejected": "Rejected",
        "superseded": "Superseded",
    }.get(s, s)


def _targets(meta: dict) -> str:
    tv = meta.get("target_versions") or {}
    bits = [f"{k} {v}" for k, v in tv.items() if v]
    return "; ".join(bits) or "—"


def render_index() -> str:
    recs = sorted(discover(), key=lambda r: r["meta"].get("id", ""))
    lines = [
        _GEN_HEADER,
        "",
        "# Methodology change proposals",
        "",
        "Suggested changes to the scoring methodology — or any other tunable",
        "parameter — drafted and reviewed *before* the engine moves. The",
        "versioned contracts are hardlines (see",
        "[`../HARDLINES.md`](../HARDLINES.md)); a proposal makes the intended",
        "change explicit, comparable, and discussable first. Lifecycle:",
        "",
        "`draft` → `under-review` → `accepted` | `rejected` | `superseded`",
        "",
        'New proposal: `python3 scripts/proposals.py new "<title>"`. Compare a',
        "proposal's params to the live engine: `python3 scripts/proposals.py",
        'compare <id>`. The format is in [`TEMPLATE.md`](TEMPLATE.md). "Published"',
        "here means pushed to the repo for review — not the user-profile",
        "`publish` privacy path.",
        "",
    ]

    by_status: dict[str, list[dict]] = {s: [] for s in STATUSES}
    for r in recs:
        by_status.setdefault(r["meta"].get("status", "draft"), []).append(r)

    open_recs = by_status["draft"] + by_status["under-review"]
    lines += ["## Open", ""]
    if open_recs:
        lines += ["| # | Proposal | Status | Version target | Summary |", "|---|---|---|---|---|"]
        for r in open_recs:
            m = r["meta"]
            link = f"[{m.get('title', '')}]({r['path'].name})"
            lines.append(
                f"| {m.get('id', '')} | {link} | {_status_label(m.get('status', ''))} "
                f"| {_targets(m)} | {m.get('summary', '')} |"
            )
    else:
        lines.append("*None open.*")
    lines.append("")

    decided = by_status["accepted"] + by_status["rejected"] + by_status["superseded"]
    lines += ["## Decided", ""]
    if decided:
        lines += ["| # | Proposal | Status | Decided | Summary |", "|---|---|---|---|---|"]
        for r in decided:
            m = r["meta"]
            link = f"[{m.get('title', '')}]({r['path'].name})"
            lines.append(
                f"| {m.get('id', '')} | {link} | {_status_label(m.get('status', ''))} "
                f"| {m.get('decided') or '—'} | {m.get('summary', '')} |"
            )
    else:
        lines.append("*None decided yet.*")
    lines.append("")
    return "\n".join(lines)


def compare_table(rec: dict) -> str:
    m = rec["meta"]
    live = live_versions()
    out = [
        f"# {m.get('id', '')} — {m.get('title', '')}",
        "",
        f"Status: **{m.get('status', '')}**",
        "",
    ]
    tv = m.get("target_versions") or {}
    vrows = []
    for k in VERSION_KEYS:
        v = tv.get(k)
        if not v:
            continue
        bump = _BUMP_RE.match(str(v))
        base = bump.group(1) if bump else "?"
        flag = "" if base == live[k] else f"  ⚠ live is {live[k]}"
        vrows.append((f"{k.upper()}_VERSION", v, flag))
    if vrows:
        out += ["## Version constants", "", "| Constant | Bump | Note |", "|---|---|---|"]
        out += [f"| {n} | {b} | {f or '—'} |" for n, b, f in vrows]
        out.append("")
    out += ["## Parameters", "", "| Param | Current | Proposed | Rationale |", "|---|---|---|---|"]
    for c in m.get("changes", []):
        out.append(
            f"| `{c.get('param', '')}` | {c.get('current', '')} | "
            f"{c.get('proposed', '')} | {c.get('rationale', '')} |"
        )
    return "\n".join(out)


# ── commands ─────────────────────────────────────────────────────────────────
def _slug(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return s or "proposal"


def _next_id() -> str:
    ids = [int(r["meta"]["id"]) for r in discover() if str(r["meta"].get("id", "")).isdigit()]
    return f"{(max(ids) + 1) if ids else 1:04d}"


def cmd_new(title: str) -> int:
    if not title.strip():
        print('usage: proposals.py new "<title>"', file=sys.stderr)
        return 2
    pid = _next_id()
    path = PROPOSALS_DIR / f"{pid}-{_slug(title)}.md"
    if path.exists():
        print(f"{path.name} already exists", file=sys.stderr)
        return 1
    live = live_versions()
    meta = {
        "id": pid,
        "title": title,
        "status": "draft",
        "authors": ["<your name>"],
        "opened": _dt.date.today().isoformat(),
        "decided": None,
        "summary": "<one-sentence summary of the change>",
        "target_versions": {
            "methodology": f"{live['methodology']} -> <next>",
            "schema": None,
            "taxonomy": None,
        },
        "changes": [
            {
                "param": "<module.param>",
                "ref": "<file or section it lives in>",
                "current": "<live value>",
                "proposed": "<new value>",
                "rationale": "<why>",
            }
        ],
        "blast_radius": ["<tests touched>", "<docs touched>", "<version bump>"],
        "references": ["docs/REFERENCES.md — <study>"],
    }
    body = _body_template()
    path.write_text(_compose(meta, body))
    print(f"wrote {path.relative_to(ROOT)}")
    render_to_disk()
    return 0


def _compose(meta: dict, body: str) -> str:
    return f"```json\n{json.dumps(meta, indent=2)}\n```\n\n{body.strip()}\n"


def _body_template() -> str:
    return (
        "## Motivation\n\nWhat problem with the current value/formula prompts this, "
        "and why now.\n\n"
        "## Detailed design\n\nThe exact change: formula, band, weight, or constant — "
        "before and after. Reference the precise code site.\n\n"
        "## Evidence\n\nThe research or measured data behind the proposed value. Tie to "
        "`docs/REFERENCES.md` where possible; mark directional vs load-bearing honestly.\n\n"
        "## Alternatives considered\n\nOther values/approaches and why they lose.\n\n"
        "## Risks & blast radius\n\nWhat breaks or shifts: tests (esp. the formula "
        "fingerprint), docs to regenerate, the version bump, cache invalidation.\n\n"
        "## Discussion\n\nOpen questions and notes captured during review.\n"
    )


def cmd_validate() -> int:
    _, errs = validate_all()
    if errs:
        print("Proposal validation failed:", file=sys.stderr)
        for e in errs:
            print(f"  - {e}", file=sys.stderr)
        return 1
    print(f"{len(discover())} proposal(s) valid.")
    return 0


def cmd_compare(pid: str) -> int:
    for r in discover():
        if r["meta"].get("id") == pid:
            print(compare_table(r))
            return 0
    print(f"no proposal with id '{pid}'", file=sys.stderr)
    return 1


def render_to_disk() -> None:
    PROPOSALS_DIR.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(render_index().rstrip() + "\n")


def cmd_render() -> int:
    render_to_disk()
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


def cmd_check() -> int:
    _, errs = validate_all()
    if errs:
        print("Proposal validation failed:", file=sys.stderr)
        for e in errs:
            print(f"  - {e}", file=sys.stderr)
        return 1
    want = render_index().rstrip() + "\n"
    have = INDEX.read_text() if INDEX.exists() else ""
    if want != have:
        print(
            "docs/proposals/README.md is stale — run "
            "`python3 scripts/proposals.py render` and commit.",
            file=sys.stderr,
        )
        return 1
    print("proposals OK; index up to date.")
    return 0


def cmd_status(pid: str, new_status: str) -> int:
    if new_status not in STATUSES:
        print(f"status must be one of {STATUSES}", file=sys.stderr)
        return 2
    for r in discover():
        if r["meta"].get("id") == pid:
            meta = r["meta"]
            meta["status"] = new_status
            if new_status in DECIDED_STATUSES and not meta.get("decided"):
                meta["decided"] = _dt.date.today().isoformat()
            r["path"].write_text(_compose(meta, r["body"]))
            print(f"{r['path'].name} → {new_status}")
            render_to_disk()
            return 0
    print(f"no proposal with id '{pid}'", file=sys.stderr)
    return 1


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 0
    cmd, rest = argv[0], argv[1:]
    if cmd == "new":
        return cmd_new(" ".join(rest))
    if cmd == "validate":
        return cmd_validate()
    if cmd == "compare" and rest:
        return cmd_compare(rest[0])
    if cmd == "render":
        return cmd_render()
    if cmd == "check":
        return cmd_check()
    if cmd == "status" and len(rest) == 2:
        return cmd_status(rest[0], rest[1])
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
