#!/usr/bin/env python3
"""@generated-source for nextmillionai/docs/methodology/DERIVATIONS.md.

Renders the machine-readable methodology registry (``nextmillionai.methodology_spec``)
— which is itself guarded against the scoring engine — into the human-readable
per-metric derivations reference. This keeps ONE source of truth: the registry
derives numbers from scoring.py, the /methodology explorer reads the registry,
and this doc is generated from the same registry. None can disagree.

Usage:
    python3 scripts/render_methodology_registry.py            # write the doc
    python3 scripts/render_methodology_registry.py --check    # CI: assert current
"""

from __future__ import annotations

import sys
from pathlib import Path

# Always render THIS repo's registry — running the script directly puts
# scripts/ (not the repo root) on sys.path, and a pip-installed copy of
# the package elsewhere would silently win the import and render a stale
# registry as a convincing no-op.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from nextmillionai.methodology_spec import PROVENANCE, SECTION_LABELS, build_spec  # noqa: E402

OUT = (
    Path(__file__).resolve().parent.parent
    / "nextmillionai"
    / "docs"
    / "methodology"
    / "DERIVATIONS.md"
)

_HEADER = """<!-- @generated by scripts/render_methodology_registry.py — DO NOT EDIT.
Edit the registry in nextmillionai/methodology_spec.py and regenerate. -->

# Per-metric derivations

*Generated from the methodology registry (`nextmillionai/methodology_spec.py`).*
This is the exhaustive reference for every number on the profile and report: the
exact code logic, our reasoning for it, and an honest **provenance** label. The
registry derives all numbers live from `scoring.py` and is guarded by
`tests/test_methodology_spec.py`; this doc is generated from it and checked in
CI, so the doc, the `/methodology` explorer, and the engine cannot disagree.

The narrative *why* is [`THESIS.md`](../../../THESIS.md); the bibliography
is [`docs/REFERENCES.md`](../../../docs/REFERENCES.md); the canonical contract is
[`SCORING-METHODOLOGY.md`](../SCORING-METHODOLOGY.md).
"""


def _provenance_section() -> list[str]:
    out = ["## Provenance — the honest class of every number", ""]
    for level, desc in PROVENANCE.items():
        out.append(f"- **{level}** — {desc}")
    out.append("")
    out.append(
        "A number's provenance is not a quality grade — it states what *kind* of "
        "claim it is, so the methodology is complete without overclaiming. "
        "*Reasoned-defaults* are chosen constants, openly versioned and listed in "
        "[Open questions](../SCORING-METHODOLOGY.md#open-questions); they recalibrate "
        "as data accrues. Meaning comes from construct validity, transparency, and "
        "this honest provenance — never from validation against a cohort, which the "
        "no-ranking, local-first design forbids."
    )
    return out


def _dimensions_section(spec: dict) -> list[str]:
    out = ["## Quality dimensions", ""]
    out.append("The composite is a mode-weighted average of these six. Each is scored")
    out.append("0–100 by mapping its sub-signals onto research-derived bands, then")
    out.append("averaging. Per-signal scaling anchors live in `scoring.py` (a reasoned")
    out.append("default flagged for hoisting + validation).")
    out.append("")
    out.append("| Dimension | Weight | Provenance | Measures | Signals | Research |")
    out.append("|---|---|---|---|---|---|")
    for d in spec["dimensions"]:
        cites = ", ".join(c["label"] for c in d["citations"]) or "—"
        signals = ", ".join(d["signals"])
        out.append(
            f"| {d['name']} | {d['weight']} | {d['provenance']} | {d['measures']} "
            f"| {signals} | {cites} |"
        )
    return out


def _metrics_sections(spec: dict) -> list[str]:
    by_sec: dict[str, list[dict]] = {}
    for m in spec["metrics"]:
        by_sec.setdefault(m["section"], []).append(m)
    out: list[str] = []
    for sec_id, label in SECTION_LABELS.items():
        items = by_sec.get(sec_id)
        if not items:
            continue
        out += ["", f"## {label}", ""]
        for m in items:
            out.append(f"### {m['label']} — {m['type']} · {m['provenance']}")
            out.append("")
            out.append(f"**How it is derived.** {m['derivation']}")
            out.append("")
            out.append(f"**Why.** {m['reasoning']}")
            if m.get("basis"):
                out.append("")
                out.append(f"**Basis / caveat.** {m['basis']}")
            for c in m.get("citations", []):
                out.append("")
                out.append(f"**Research.** {c['label']} — {c['finding']}")
            out.append("")
    return out


def render() -> str:
    spec = build_spec()
    lines = [_HEADER, ""]
    lines += _provenance_section()
    lines += [""]
    lines += _dimensions_section(spec)
    lines += _metrics_sections(spec)
    lines += [
        "---",
        "",
        f"*Methodology version {spec['methodologyVersion']} · "
        f"schema {spec['schemaVersion']} · taxonomy {spec['taxonomyVersion']}. "
        "Regenerate with `python3 scripts/render_methodology_registry.py`.*",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(
                "DERIVATIONS.md is stale — run "
                "`python3 scripts/render_methodology_registry.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print("DERIVATIONS.md is up to date.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
